import React, { useState, useEffect, useRef } from "react"
import { DropZone } from "@/components/shared/DropZone"
import { Download, ArrowLeft, Loader2, CheckCircle, Type, Image as ImageIcon, Trash2, Plus, Sparkles } from "lucide-react"
import { usePremium } from "@/hooks/usePremium"
import { toast } from "sonner"
import * as fabric from "fabric"

const FAMOUS_WATERMARKS = [
  { name: "ChatGPT", color: "#10a37f", text: "Generated by ChatGPT" },
  { name: "Gemini", color: "#4285f4", text: "AI by Gemini" },
  { name: "Groq", color: "#f55036", text: "GROQ SPEED" },
  { name: "Upstash", color: "#00e9a3", text: "Upstash Serverless" },
  { name: "Vanity", color: "#F59E0B", text: "Edited with Vanity" },
]

export function ImageWatermark() {
  const { validateFiles } = usePremium()
  const [file, setFile] = useState<File | null>(null)
  const [isProcessing, setIsProcessing] = useState(false)
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const fabricCanvas = useRef<fabric.Canvas | null>(null)
  const [activeTab, setActiveTab] = useState<"text" | "image" | "famous">("text")

  useEffect(() => {
    if (!file) return
    
    // Revoke previous URLs if any
    const img = new Image()
    const objectUrl = URL.createObjectURL(file)
    img.src = objectUrl
    
    img.onload = () => {
      if (!canvasRef.current) return
      
      // Initialize Fabric Canvas
      const canvas = new fabric.Canvas(canvasRef.current, {
        width: 800,
        height: 600,
        backgroundColor: "#000"
      })
      fabricCanvas.current = canvas

      fabric.FabricImage.fromURL(objectUrl).then((fbImg) => {
        // Scale image to fit canvas
        const scale = Math.min(800 / fbImg.width!, 600 / fbImg.height!)
        fbImg.scale(scale)
        fbImg.set({
            selectable: false,
            evented: false,
            left: (800 - fbImg.width! * scale) / 2,
            top: (600 - fbImg.height! * scale) / 2
        })
        canvas.add(fbImg)
        canvas.centerObject(fbImg)
        canvas.renderAll()
      })
    }

    return () => {
      URL.revokeObjectURL(objectUrl)
      if (fabricCanvas.current) {
        fabricCanvas.current.dispose()
        fabricCanvas.current = null
      }
    }
  }, [file])

  const addTextWatermark = () => {
    if (!fabricCanvas.current) return
    const text = new fabric.IText("WATERMARK", {
      left: 100,
      top: 100,
      fontFamily: "Syne",
      fontSize: 40,
      fill: "rgba(255,255,255,0.5)",
    })
    fabricCanvas.current.add(text)
    fabricCanvas.current.setActiveObject(text)
  }

  const addImageWatermark = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file || !fabricCanvas.current) return
    
    const url = URL.createObjectURL(file)
    fabric.FabricImage.fromURL(url).then((img) => {
      img.scale(0.2)
      fabricCanvas.current?.add(img)
      fabricCanvas.current?.centerObject(img)
      fabricCanvas.current?.setActiveObject(img)
      URL.revokeObjectURL(url)
    })
  }

  const addFamousWatermark = (w: typeof FAMOUS_WATERMARKS[0]) => {
    if (!fabricCanvas.current) return
    const group = new fabric.Group([
      new fabric.Rect({
        width: 250,
        height: 40,
        fill: w.color,
        rx: 10,
        ry: 10,
        opacity: 0.8
      }),
      new fabric.IText(w.text, {
        fontSize: 14,
        fill: "#fff",
        left: 20,
        top: 12,
        fontFamily: "Inter"
      })
    ], {
      left: 150,
      top: 150
    })
    fabricCanvas.current.add(group)
    fabricCanvas.current.setActiveObject(group)
  }

  const deleteSelected = () => {
    const active = fabricCanvas.current?.getActiveObject()
    if (active) {
      fabricCanvas.current?.remove(active)
      fabricCanvas.current?.discardActiveObject()
      fabricCanvas.current?.renderAll()
    }
  }

  const handleDownload = () => {
    if (!fabricCanvas.current) return
    setIsProcessing(true)
    
    // Get the data URL at high scale for quality
    const dataUrl = fabricCanvas.current.toDataURL({
      format: "png",
      quality: 1
    })
    
    const a = document.createElement("a")
    a.href = dataUrl
    a.download = `vanity-watermarked-${Date.now()}.png`
    a.click()
    
    setIsProcessing(false)
    toast.success("Watermarked image exported!")
  }

  if (!file) {
    return (
      <div className="max-w-2xl mx-auto py-12 text-center">
         <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-full mb-6 text-primary">
            <Sparkles className="w-8 h-8" />
         </div>
        <h1 className="text-4xl font-bold font-syne mb-1">Deep Watermark</h1>
        <p className="text-muted-foreground text-lg mb-8">
          Add interactive text, images, or branded watermarks with full control.
        </p>
        <DropZone onDrop={(f) => { if (validateFiles(f)) setFile(f[0]); }} accept={{ "image/*": [] }} />
      </div>
    )
  }

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      <div className="flex items-center justify-between mt-4">
        <div>
          <h1 className="text-3xl font-bold font-syne mb-2">Watermark Editor</h1>
          <p className="text-muted-foreground text-sm">Rotate, scale, and place watermarks anywhere.</p>
        </div>
        <button onClick={() => setFile(null)} className="text-sm font-medium text-muted-foreground hover:text-foreground flex items-center gap-2">
          <ArrowLeft className="w-4 h-4" /> Change Image
        </button>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-8 pb-12">
        {/* Editor sidebar */}
        <div className="xl:col-span-1 space-y-6">
          <div className="glass-panel p-6 rounded-xl space-y-6">
            <div className="flex p-1 bg-white/5 rounded-lg mb-4">
              <button 
                onClick={() => setActiveTab("text")}
                className={`flex-1 flex flex-col items-center py-3 rounded-md transition-all ${activeTab === "text" ? "bg-primary text-primary-foreground font-bold shadow-lg" : "text-muted-foreground hover:text-foreground"}`}
              >
                <Type className="w-5 h-5 mb-1" />
                <span className="text-[10px] uppercase font-bold tracking-tighter">Text</span>
              </button>
              <button 
                onClick={() => setActiveTab("image")}
                className={`flex-1 flex flex-col items-center py-3 rounded-md transition-all ${activeTab === "image" ? "bg-primary text-primary-foreground font-bold shadow-lg" : "text-muted-foreground hover:text-foreground"}`}
              >
                <ImageIcon className="w-5 h-5 mb-1" />
                <span className="text-[10px] uppercase font-bold tracking-tighter">Image</span>
              </button>
              <button 
                onClick={() => setActiveTab("famous")}
                className={`flex-1 flex flex-col items-center py-3 rounded-md transition-all ${activeTab === "famous" ? "bg-primary text-primary-foreground font-bold shadow-lg" : "text-muted-foreground hover:text-foreground"}`}
              >
                <CheckCircle className="w-5 h-5 mb-1" />
                <span className="text-[10px] uppercase font-bold tracking-tighter">Branded</span>
              </button>
            </div>

            {activeTab === "text" && (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                <p className="text-xs text-muted-foreground">Add editable text watermarks.</p>
                <button 
                  onClick={addTextWatermark}
                  className="w-full py-4 bg-white/5 border border-dashed border-white/20 rounded-xl flex flex-col items-center hover:bg-white/10 transition-all group"
                >
                  <Plus className="w-6 h-6 mb-2 text-primary group-hover:scale-110 transition-transform" />
                  <span className="text-sm font-bold">Add Text Layer</span>
                </button>
              </div>
            )}

            {activeTab === "image" && (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                <p className="text-xs text-muted-foreground">Upload custom PNG or SVG watermarks.</p>
                <label className="w-full py-4 bg-white/5 border border-dashed border-white/20 rounded-xl flex flex-col items-center hover:bg-white/10 transition-all cursor-pointer group">
                  <ImageIcon className="w-6 h-6 mb-2 text-primary group-hover:scale-110 transition-transform" />
                  <span className="text-sm font-bold">Upload PNG Watermark</span>
                  <input type="file" className="hidden" accept="image/png" onChange={addImageWatermark} />
                </label>
              </div>
            )}

            {activeTab === "famous" && (
              <div className="grid grid-cols-1 gap-2 animate-in fade-in slide-in-from-bottom-2">
                {FAMOUS_WATERMARKS.map(w => (
                  <button 
                    key={w.name}
                    onClick={() => addFamousWatermark(w)}
                    className="flex items-center justify-between p-3 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 transition-all text-left group"
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-2 h-2 rounded-full" style={{ backgroundColor: w.color }} />
                      <span className="text-sm font-medium">{w.name}</span>
                    </div>
                    <Plus className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity" />
                  </button>
                ))}
              </div>
            )}

            <div className="pt-6 border-t border-white/10 space-y-4">
              <button 
                onClick={deleteSelected}
                className="w-full py-3 text-sm font-bold text-destructive hover:bg-destructive/10 rounded-lg flex items-center justify-center gap-2 transition-all"
              >
                <Trash2 className="w-4 h-4" /> Delete Selected
              </button>
              
              <button 
                onClick={handleDownload}
                disabled={isProcessing}
                className="w-full py-4 bg-primary text-primary-foreground font-bold rounded-xl flex items-center justify-center gap-3 shadow-[0_0_30px_rgba(245,158,11,0.2)] hover:scale-[1.02] active:scale-95 transition-all disabled:opacity-50"
              >
                {isProcessing ? <Loader2 className="animate-spin" /> : <Download className="w-5 h-5" />}
                Export Final Result
              </button>
            </div>
          </div>
          
          <div className="glass-panel p-4 rounded-xl">
             <h4 className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-4">Pro Tip</h4>
             <p className="text-[10px] leading-relaxed text-muted-foreground">
               Double-click text to edit. Use corners to scale. Use the top handle to rotate. You can add as many watermarks as you need!
             </p>
          </div>
        </div>

        {/* Canvas Area */}
        <div className="xl:col-span-3 glass-panel p-4 rounded-2xl flex items-center justify-center bg-[#050505] min-h-[650px] overflow-auto shadow-2xl relative">
          <div className="absolute top-4 left-4 z-10">
             <span className="px-3 py-1 bg-white/10 backdrop-blur rounded-full text-[10px] font-bold text-white/50 border border-white/10">PREVIEW CANVAS</span>
          </div>
          <canvas ref={canvasRef} />
        </div>
      </div>
    </div>
  )
}
